# >>> jira-cli skill >>>
# Generated by the jira-cli skill. Do not edit here; edit the skill template.
jira() {
  if command -v docker >/dev/null 2>&1; then
    local img="__JIRA_CLI_IMAGE__"
    local -a _jira_args=(--rm --user "$(id -u):$(id -g)" -e HOME=/home/jira -e "JIRA_API_TOKEN=${JIRA_API_TOKEN:-}" -v "$HOME/.config/.jira:/home/jira/.config/.jira")
    if [ -t 0 ] && [ -t 1 ]; then _jira_args+=(-it); fi
    command docker run "${_jira_args[@]}" --entrypoint jira "$img" "$@"
  elif [ -x "$HOME/.local/bin/jira" ]; then
    command "$HOME/.local/bin/jira" "$@"
  else
    echo "jira-cli: no hay Docker ni ~/.local/bin/jira. Corre scripts/install.sh de la skill." >&2
    return 1
  fi
}

# My assigned Jira tasks
alias jm='jira issue list -a$(jira me)'
# <<< jira-cli skill <<<
