# >>> jira-cli skill >>>
# Generated by the jira-cli skill. Do not edit here; edit the skill template.
function jira --description 'JiraCLI (Docker __JIRA_CLI_IMAGE__)'
    if command -v docker >/dev/null 2>&1
        set -l img __JIRA_CLI_IMAGE__
        set -l args --rm \
            --user (id -u):(id -g) \
            -e HOME=/home/jira \
            -e JIRA_API_TOKEN=$JIRA_API_TOKEN \
            -v ~/.config/.jira:/home/jira/.config/.jira
        if isatty stdin; and isatty stdout
            set -a args -it
        end
        command docker run $args --entrypoint jira $img $argv
    else if test -x ~/.local/bin/jira
        command ~/.local/bin/jira $argv
    else
        echo "jira-cli: no hay Docker ni ~/.local/bin/jira. Corre scripts/install.sh de la skill." >&2
        return 1
    end
end
# <<< jira-cli skill <<<
