#!/usr/bin/env sh
# Generated by the jira-cli skill. Do not edit here; edit the skill template.
#
# Executable `jira` shim (Docker-only). Unlike the rc-loaded shell function,
# this works in every shell — interactive or not, including the non-interactive
# shell an agent uses — so nobody has to source an rc file to get `jira`.
#
# Do not call this file directly; it is installed as `jira` on PATH by
# scripts/install_wrapper.sh.

set -eu

img="__JIRA_CLI_IMAGE__"

if ! command -v docker >/dev/null 2>&1; then
  echo "jira-cli: Docker no está instalado. Corre scripts/install.sh de la skill." >&2
  exit 1
fi

cfg="${JIRA_CONFIG_DIR:-$HOME/.config/.jira}"
mkdir -p "$cfg" 2>/dev/null || true

# Allocate a TTY only when one is attached so pipelines keep working
# (`jira ... --plain | grep`, `$(jira me)`).
tty=""
if [ -t 0 ] && [ -t 1 ]; then tty=1; fi

# shellcheck disable=SC2086
exec docker run \
  --rm \
  --user "$(id -u):$(id -g)" \
  -e HOME=/home/jira \
  -e "JIRA_API_TOKEN=${JIRA_API_TOKEN:-}" \
  -v "$cfg:/home/jira/.config/.jira" \
  ${tty:+-it} \
  --entrypoint jira "$img" "$@"
