#!/usr/bin/env bash
# install_completions.sh — install shell completions for the `jira` command.
#
# Completions are generated by jira-cli itself and keyed on the command name,
# so they work with the shell function installed by install_wrapper.sh.
#
# Usage: install_completions.sh [fish|bash|zsh]   (defaults to $SHELL)
set -euo pipefail
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
. "$SELF_DIR/_lib.sh"

shell="${1:-$(detect_shell)}"
tmp="$(mktemp "${TMPDIR:-/tmp}/jira-completion.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

case "$shell" in
  fish)
    dest="$HOME/.config/fish/completions/_jira.fish"
    mkdir -p "$(dirname "$dest")"
    jira_cmd completion fish >"$tmp"
    ;;
  bash)
    dest="$HOME/.local/share/bash-completion/completions/jira"
    mkdir -p "$(dirname "$dest")"
    jira_cmd completion bash >"$tmp"
    ;;
  zsh)
    dest="$HOME/.zfunc/_jira"
    mkdir -p "$(dirname "$dest")"
    jira_cmd completion zsh >"$tmp"
    if ! grep -qF 'fpath=(~/.zfunc' "$HOME/.zshrc" 2>/dev/null; then
      replace_block "$HOME/.zshrc" \
        '# >>> jira-cli skill:zfunc >>>' \
        '# <<< jira-cli skill:zfunc <<<' \
        '# >>> jira-cli skill:zfunc >>>
fpath=(~/.zfunc $fpath)
# <<< jira-cli skill:zfunc <<<' || true
      ok "fpath de zsh actualizado (~/.zfunc)"
    fi
    ;;
  *)
    die "Shell no soportado: '$shell'. Usa fish, bash o zsh."
    ;;
esac

if [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
  ok "Completions sin cambios: $dest"
else
  mv "$tmp" "$dest"
  trap - EXIT
  ok "Completions instaladas: $dest"
fi
